[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native"]

[env]
CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG = "true"
CARGO_PROFILE_DEV_BUILD_OVERRIDE_OPT_LEVEL = "0"
